import type { Client, Employee, EmployeePerformance, Equipment, Job, JobCategory, JobPriority, JobStatus, MonthlyReport, Notification, OperationsData, SupervisorActivity, WorkloadDistribution } from "@/types/operations";

const START = new Date("2026-02-01T08:00:00.000Z");
const END = new Date("2026-07-23T16:00:00.000Z");
const sections = ["Paper Machine", "Pulp Preparation", "Boiler House", "Power House", "Utilities", "Water Treatment", "Compressed Air", "Workshop", "Packaging", "Stores", "Effluent Treatment", "Administration"];
const categories: JobCategory[] = [
  ["breakdown", "Breakdown Maintenance", "#C4342D", 8], ["preventive", "Preventive Maintenance", "#16803C", 6], ["corrective", "Corrective Maintenance", "#1F6FEB", 10], ["emergency", "Emergency Repair", "#B91C1C", 5], ["fabrication", "Fabrication", "#7C3AED", 16], ["welding", "Welding", "#B96A00", 10], ["machining", "Machining", "#0F766E", 14], ["bearing", "Bearing Replacement", "#9333EA", 8], ["pump", "Pump Repair", "#0369A1", 12], ["motor", "Motor Replacement", "#DC2626", 14], ["alignment", "Alignment", "#2563EB", 7], ["inspection", "Inspection", "#059669", 4], ["shutdown", "Shutdown Maintenance", "#475569", 18], ["lubrication", "Lubrication", "#65A30D", 3], ["valve", "Valve Repair", "#EA580C", 9],
].map(([id, name, color, targetHours]) => ({ id: id as string, name: name as string, color: color as string, targetHours: targetHours as number }));
const supervisors = ["Peter Mwangi", "David Mutua", "Naomi Wanjiru", "Samuel Kariuki"];
const technicians = ["Amina Hassan", "Peter Otieno", "Grace Njeri", "Brian Mutua", "Jane Wambui", "Kevin Onyango", "Faith Chebet", "John Kamau", "Lydia Achieng", "Samuel Kiplagat", "Irene Wairimu", "David Mwangi", "Mercy Atieno", "Allan Kiprotich", "Ruth Wanjiku", "Martin Ouma", "Lucy Muthoni", "James Karanja", "Esther Chepkirui", "Victor Maina", "Beatrice Wambui", "Joseph Omondi", "Caroline Nyambura", "Dennis Kiptoo", "Mary Naliaka", "Paul Mutiso"];
const equipmentSeeds = ["PM-01|Paper Machine No. 1", "PM-02|Paper Machine No. 2", "HP-01|Hydrapulper", "AC-01|Air Compressor", "BL-01|Steam Boiler", "VP-02|Vacuum Pump", "CV-07|Conveyor", "GB-04|Gearbox", "HX-01|Heat Exchanger", "PP-05|Process Pump", "RF-01|Refiner", "CH-02|Chest Agitator", "FD-01|Forced Draft Fan", "ID-01|Induced Draft Fan", "TG-01|Turbogenerator", "TR-01|Main Transformer", "CT-01|Cooling Tower", "WT-01|Water Treatment Plant", "DA-01|Dry Air Compressor", "LH-01|Lathe Machine", "ML-01|Milling Machine", "CR-01|Overhead Crane", "WR-01|Winder", "SL-01|Slitter", "PK-01|Packaging Line", "ET-01|Effluent Pump", "SV-01|Sewage Vacuum Pump", "FN-01|Paper Machine Fan", "MC-01|Motor Control Centre", "AG-01|Stock Agitator", "SC-01|Screw Conveyor", "PR-01|Press Roll", "DR-01|Dryer Cylinder", "CL-01|Calender", "RE-01|Reel Stand"];
let seed = 81721;
const random = () => { seed = (seed * 1664525 + 1013904223) % 4294967296; return seed / 4294967296; };
const iso = (date: Date) => date.toISOString();
const addHours = (date: Date, hours: number) => new Date(date.getTime() + hours * 3600000);
const monthKey = (value: string) => value.slice(0, 7);

function generateEmployees(): Employee[] { const people = supervisors.map((name, index) => ({ id: `sup-${index + 1}`, name, role: "supervisor" as const, email: `${name.toLowerCase().replace(" ", ".")}@eastafricapapermills.co.ke`, phone: `+254 700 100 ${String(index + 1).padStart(3, "0")}`, capabilities: ["Maintenance planning", "Supervisor verification"], availability: "active" as const, joinedAt: iso(addHours(START, -10000 - index * 100)) })); return [...people, ...technicians.map((name, index) => ({ id: `tech-${String(index + 1).padStart(2, "0")}`, name, role: "technician" as const, email: `${name.toLowerCase().replace(" ", ".")}@eastafricapapermills.co.ke`, phone: `+254 711 ${String(200000 + index).slice(1)}`, capabilities: [categories[index % categories.length].name, categories[(index + 4) % categories.length].name], availability: index === 5 || index === 17 ? "unavailable" as const : "active" as const, joinedAt: iso(addHours(START, -9000 - index * 90)) }))]; }
function generateClients(): Client[] { return Array.from({ length: 120 }, (_, index) => { const section = sections[index % sections.length]; return { id: `request-${String(index + 1).padStart(3, "0")}`, name: `${section} Request ${String(Math.floor(index / sections.length) + 1).padStart(2, "0")}`, contactName: `${section} Shift Team`, phone: "+254 700 000 000", email: `${section.toLowerCase().replaceAll(" ", ".")}@eastafricapapermills.co.ke`, location: section, createdAt: iso(addHours(START, -2000 - index * 8)) }; }); }
function generateEquipment(): Equipment[] { return Array.from({ length: 70 }, (_, index) => { const [id, name] = (equipmentSeeds[index % equipmentSeeds.length] + (index >= equipmentSeeds.length ? `-${Math.floor(index / equipmentSeeds.length) + 1}|${equipmentSeeds[index % equipmentSeeds.length].split("|")[1]} Unit ${Math.floor(index / equipmentSeeds.length) + 1}` : "")).split("|"); const status = index % 19 === 0 ? "under_maintenance" : index % 13 === 0 ? "standby" : "operational"; return { id, name, plantSection: sections[index % sections.length], criticality: index % 11 === 0 ? "critical" : index % 4 === 0 ? "high" : index % 3 === 0 ? "low" : "medium", status, manufacturer: ["Valmet", "Andritz", "Siemens", "Atlas Copco", "Sulzer"][index % 5], installationDate: `${2008 + (index % 14)}-${String((index % 12) + 1).padStart(2, "0")}-15`, lastServiceDate: `2026-${String((index % 6) + 1).padStart(2, "0")}-${String((index % 26) + 1).padStart(2, "0")}` }; }); }
function statusFor(index: number): JobStatus { if (index < 750) return index % 42 === 0 ? "repeat_fault" : index % 18 === 0 ? "cancelled" : index % 3 === 0 ? "closed" : "completed"; return (["reported", "approved", "assigned", "in_progress", "waiting_spare_parts", "waiting_production_clearance", "pending_supervisor_verification", "repeat_fault"] as JobStatus[])[(index - 750) % 8]; }
function priorityFor(index: number): JobPriority { return index % 31 === 0 ? "critical" : index % 8 === 0 ? "high" : index % 6 === 0 ? "low" : index % 10 === 0 ? "scheduled" : "medium"; }
function generateJobs(employees: Employee[], clients: Client[], equipment: Equipment[]): Job[] { const techs = employees.filter((employee) => employee.role === "technician" && employee.availability === "active"); const leads = employees.filter((employee) => employee.role === "supervisor"); return Array.from({ length: 780 }, (_, index) => { const current = index >= 750; const createdAt = current ? addHours(END, -((index - 750) * 9 + 4)) : new Date(START.getTime() + Math.floor((index / 749) * (END.getTime() - START.getTime()))); const machine = equipment[index % equipment.length]; const category = categories[index % categories.length]; const status = statusFor(index); const technician = status === "reported" || status === "approved" ? undefined : techs[index % techs.length]; const completed = !current && status !== "cancelled"; const completionHours = category.targetHours + (index % 6) * 2; const completedAt = completed ? addHours(createdAt, completionHours) : undefined; const emergency = category.id === "emergency" || index % 65 === 0; const repeat = status === "repeat_fault" || index % 43 === 0; return { id: `work-order-${String(index + 1).padStart(4, "0")}`, reference: `WO-${String(3201 + index).padStart(4, "0")}`, title: `${category.name} — ${machine.name}`, description: `${emergency ? "Urgent response required. " : ""}${machine.name} in ${machine.plantSection}: inspection and maintenance work requested.`, clientId: clients[index % clients.length].id, categoryId: category.id, equipmentId: machine.id, plantSection: machine.plantSection, priority: emergency ? "critical" : priorityFor(index), status, primaryTechnicianId: technician?.id, supportingTechnicianIds: index % 12 === 0 && technician ? [techs[(index + 3) % techs.length].id] : [], supervisorId: leads[index % leads.length].id, createdAt: iso(createdAt), updatedAt: iso(addHours(createdAt, completed ? completionHours : 2 + (index % 12))), scheduledFor: iso(addHours(createdAt, 8 + (index % 48))), completedAt: completedAt ? iso(completedAt) : undefined, resolution: completed ? `${category.name} completed; ${machine.name} tested and returned to service.` : undefined, cancellationReason: status === "cancelled" ? "Production schedule changed before maintenance window." : undefined, blockerReason: status === "waiting_spare_parts" ? "Awaiting approved spare parts from Stores." : status === "waiting_production_clearance" ? "Awaiting production clearance." : undefined, repeatGroupId: repeat ? `repeat-${machine.id}` : undefined, activity: [{ id: `activity-${index}`, createdAt: iso(createdAt), actor: leads[index % leads.length].name, type: "created", message: `Work order reported for ${machine.id}.` }] }; }); }
function reportsFor(jobs: Job[]): MonthlyReport[] { return ["2026-02", "2026-03", "2026-04", "2026-05", "2026-06", "2026-07"].map(month => { const listed = jobs.filter(job => monthKey(job.createdAt) === month); const completed = listed.filter(job => Boolean(job.completedAt)); const hours = completed.map(job => (new Date(job.completedAt!).getTime() - new Date(job.createdAt).getTime()) / 3600000); return { month, jobsCreated: listed.length, jobsCompleted: completed.length, jobsCancelled: listed.filter(job => job.status === "cancelled").length, jobsBlocked: listed.filter(job => job.status === "waiting_spare_parts" || job.status === "waiting_production_clearance").length, jobsArchived: listed.filter(job => job.status === "closed").length, averageCompletionHours: Number((hours.reduce((a, b) => a + b, 0) / hours.length || 0).toFixed(1)), categoryBreakdown: Object.fromEntries(categories.map(category => [category.id, listed.filter(job => job.categoryId === category.id).length])) }; }); }
function workloadFor(employees: Employee[], jobs: Job[]): WorkloadDistribution[] { const open: JobStatus[] = ["assigned", "in_progress", "waiting_spare_parts", "waiting_production_clearance", "pending_supervisor_verification", "repeat_fault"]; return employees.filter(employee => employee.role === "technician").map(employee => { const assigned = jobs.filter(job => job.primaryTechnicianId === employee.id); return { employeeId: employee.id, openJobs: assigned.filter(job => open.includes(job.status)).length, scheduledJobs: assigned.filter(job => job.priority === "scheduled").length, inProgressJobs: assigned.filter(job => job.status === "in_progress").length, blockedJobs: assigned.filter(job => job.status === "waiting_spare_parts" || job.status === "waiting_production_clearance").length }; }); }
function createOperationsData(): OperationsData { seed = 81721; const employees = generateEmployees(); const clients = generateClients(); const equipment = generateEquipment(); const jobs = generateJobs(employees, clients, equipment); const workloadDistribution = workloadFor(employees, jobs); const employeePerformance: EmployeePerformance[] = workloadDistribution.map(item => { const completed = jobs.filter(job => job.primaryTechnicianId === item.employeeId && job.completedAt); const average = completed.reduce((sum, job) => sum + (new Date(job.completedAt!).getTime() - new Date(job.createdAt).getTime()) / 3600000, 0) / completed.length; return { employeeId: item.employeeId, completedJobs: completed.length, activeJobs: item.openJobs, averageCompletionHours: Number((average || 0).toFixed(1)), workloadLevel: item.openJobs >= 5 ? "high" : item.openJobs >= 2 ? "balanced" : "available" }; }); const supervisorActivity: SupervisorActivity[] = employees.filter(employee => employee.role === "supervisor").map(employee => { const owned = jobs.filter(job => job.supervisorId === employee.id); return { supervisorId: employee.id, jobsCreated: owned.length, jobsUpdated: owned.length, assignmentsMade: owned.filter(job => job.primaryTechnicianId).length, completionsRecorded: owned.filter(job => job.completedAt).length }; }); const notifications: Notification[] = jobs.filter(job => job.priority === "critical" || job.status === "waiting_spare_parts" || job.status === "pending_supervisor_verification").slice(-18).reverse().map((job, index) => ({ id: `notification-${index}`, type: job.priority === "critical" ? "urgent" : job.status === "waiting_spare_parts" ? "blocked" : "assignment", title: job.priority === "critical" ? `Emergency breakdown: ${job.equipmentId}` : job.status === "waiting_spare_parts" ? `${job.equipmentId} awaiting spare parts` : `Supervisor verification pending for ${job.reference}`, message: `${job.reference}: ${job.title}`, jobId: job.id, createdAt: job.updatedAt, read: index > 5 })); return { generatedAt: iso(END), employees, clients, equipment, categories, jobs, notifications, monthlyReports: reportsFor(jobs), employeePerformance, supervisorActivity, workloadDistribution }; }
export const operationsData = createOperationsData();
export const getOperationsData = () => operationsData;
