"use client";

import { useEffect, useId, useRef } from "react";
import { ChevronLeft, ChevronRight, Info, Search, X } from "lucide-react";
import { cn } from "@/lib/utils";

export function Button({ className, variant = "primary", ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "secondary" | "ghost" | "danger" }) { const styles = { primary:"bg-primary text-primary-foreground hover:opacity-90", secondary:"bg-secondary text-secondary-foreground hover:bg-accent", ghost:"hover:bg-muted", danger:"bg-danger text-white hover:opacity-90" }; return <button className={cn("inline-flex min-h-10 items-center justify-center gap-2 rounded-lg px-4 text-sm font-semibold transition-colors disabled:pointer-events-none disabled:opacity-50", styles[variant], className)} {...props} />; }
export function Input({ label, id, error, className, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label?: string; error?: string }) { const generatedId = useId(); const inputId = id ?? generatedId; return <label className="grid gap-1.5 text-sm font-medium text-foreground">{label && <span>{label}</span>}<input id={inputId} className={cn("h-10 rounded-lg border bg-card px-3 text-sm text-card-foreground placeholder:text-muted-foreground", error && "border-danger", className)} aria-invalid={Boolean(error)} {...props} />{error && <span className="text-xs text-danger">{error}</span>}</label>; }
export function Select({ label, children, className, ...props }: React.SelectHTMLAttributes<HTMLSelectElement> & { label?: string }) { const id = useId(); return <label className="grid gap-1.5 text-sm font-medium">{label && <span>{label}</span>}<select id={id} className={cn("h-10 rounded-lg border bg-card px-3 text-sm text-card-foreground", className)} {...props}>{children}</select></label>; }
export function Card({ className, children }: React.PropsWithChildren<{ className?: string }>) { return <section className={cn("rounded-xl border bg-card p-5 text-card-foreground shadow-sm", className)}>{children}</section>; }
export function StatisticCard({ label, value, change }: { label: string; value: string; change: string }) { return <Card><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-semibold tracking-tight">{value}</p><p className="mt-2 text-xs font-medium text-success">{change}</p></Card>; }
export function StatusBadge({ children, status = "neutral" }: React.PropsWithChildren<{ status?: "neutral" | "success" | "warning" | "danger" | "info" }>) { const styles = { neutral:"bg-muted text-muted-foreground", success:"bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300", warning:"bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-300", danger:"bg-red-100 text-red-800 dark:bg-red-950 dark:text-red-300", info:"bg-blue-100 text-blue-800 dark:bg-blue-950 dark:text-blue-300" }; return <span className={cn("inline-flex items-center rounded-full px-2.5 py-1 text-xs font-semibold", styles[status])}>{children}</span>; }
export function Avatar({ name, size = "md" }: { name: string; size?: "sm" | "md" | "lg" }) { const initials = name.split(" ").map((word) => word[0]).join("").slice(0, 2); return <span className={cn("inline-grid place-items-center rounded-full bg-secondary font-semibold text-secondary-foreground", size === "sm" ? "h-8 w-8 text-xs" : size === "lg" ? "h-12 w-12 text-base" : "h-10 w-10 text-sm")} aria-label={name}>{initials}</span>; }
export function SearchBox({ placeholder = "Search" }: { placeholder?: string }) { return <label className="flex h-10 items-center gap-2 rounded-lg border bg-card px-3 text-muted-foreground"><Search className="h-4 w-4" /><span className="sr-only">{placeholder}</span><input className="min-w-0 flex-1 bg-transparent text-sm text-foreground outline-none placeholder:text-muted-foreground" placeholder={placeholder} type="search" /></label>; }
export function EmptyState({ title, description }: { title: string; description: string }) { return <Card className="grid min-h-48 place-items-center text-center"><div><div className="mx-auto grid h-10 w-10 place-items-center rounded-full bg-secondary text-secondary-foreground"><Info className="h-5 w-5" /></div><h3 className="mt-3 font-semibold">{title}</h3><p className="mt-1 max-w-sm text-sm text-muted-foreground">{description}</p></div></Card>; }
export function Skeleton({ className }: { className?: string }) { return <div aria-label="Loading" className={cn("animate-pulse rounded-md bg-muted", className)} />; }
export function Tabs({ active, onChange, tabs }: { active: string; onChange: (tab: string) => void; tabs: string[] }) { return <div role="tablist" aria-label="Component tabs" className="flex gap-1 overflow-auto border-b">{tabs.map((tab) => <button key={tab} role="tab" aria-selected={active === tab} className={cn("border-b-2 px-3 py-2 text-sm font-medium", active === tab ? "border-primary text-primary" : "border-transparent text-muted-foreground hover:text-foreground")} onClick={() => onChange(tab)}>{tab}</button>)}</div>; }
export function Breadcrumbs({ items }: { items: string[] }) { return <nav aria-label="Breadcrumb"><ol className="flex flex-wrap items-center gap-2 text-sm text-muted-foreground">{items.map((item, index) => <li className="flex items-center gap-2" key={item}>{index > 0 && <span aria-hidden>/</span>}<span className={index === items.length - 1 ? "font-medium text-foreground" : ""}>{item}</span></li>)}</ol></nav>; }
export function Pagination() { return <nav className="flex items-center gap-1" aria-label="Pagination"><Button variant="ghost" aria-label="Previous page" className="min-h-9 px-2"><ChevronLeft className="h-4 w-4" /></Button><Button aria-current="page" className="min-h-9 px-3">1</Button><Button variant="ghost" className="min-h-9 px-3">2</Button><Button variant="ghost" className="min-h-9 px-3">3</Button><Button variant="ghost" aria-label="Next page" className="min-h-9 px-2"><ChevronRight className="h-4 w-4" /></Button></nav>; }
export function DataTable() { return <div className="overflow-x-auto rounded-xl border"><table className="min-w-full text-left text-sm"><caption className="sr-only">Example jobs table</caption><thead className="bg-muted text-muted-foreground"><tr><th className="px-4 py-3 font-semibold">Job</th><th className="px-4 py-3 font-semibold">Owner</th><th className="px-4 py-3 font-semibold">Status</th></tr></thead><tbody><tr className="border-t"><td className="px-4 py-3 font-medium">OPX-001</td><td className="px-4 py-3">A. Wanjiku</td><td className="px-4 py-3"><StatusBadge status="info">Assigned</StatusBadge></td></tr><tr className="border-t"><td className="px-4 py-3 font-medium">OPX-002</td><td className="px-4 py-3">P. Otieno</td><td className="px-4 py-3"><StatusBadge status="success">Complete</StatusBadge></td></tr></tbody></table></div>; }
export function Modal({ open, onClose, title, children }: React.PropsWithChildren<{ open: boolean; onClose: () => void; title: string }>) { const dialogRef = useRef<HTMLDivElement>(null); useEffect(() => { if (!open) return; dialogRef.current?.focus(); const handler = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, [open, onClose]); if (!open) return null; return <div className="fixed inset-0 z-[60] grid place-items-center bg-slate-950/50 p-4" role="presentation" onMouseDown={onClose}><div ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="dialog-title" tabIndex={-1} className="w-full max-w-md rounded-xl border bg-card p-5 shadow-xl" onMouseDown={(event) => event.stopPropagation()}><div className="flex items-center justify-between gap-4"><h2 id="dialog-title" className="text-lg font-semibold">{title}</h2><button className="rounded-md p-1 text-muted-foreground hover:bg-muted" onClick={onClose} aria-label="Close dialog"><X className="h-5 w-5" /></button></div><div className="mt-4">{children}</div></div></div>; }
export const Dialog = Modal;
