import type { Employee, Job } from "@/types/operations";

const openStatuses = ["assigned", "scheduled", "in_progress", "blocked"];
const months = ["2026-02", "2026-03", "2026-04", "2026-05", "2026-06", "2026-07"];

export function employeeJobs(employeeId: string, jobs: Job[]) { return jobs.filter((job) => job.primaryTechnicianId === employeeId); }
export function employeeMetrics(employee: Employee, jobs: Job[]) { const assigned = employeeJobs(employee.id, jobs); const completed = assigned.filter((job) => Boolean(job.completedAt)); const active = assigned.filter((job) => openStatuses.includes(job.status)); const repeated = completed.filter((job) => Boolean(job.repeatGroupId)); const averageHours = completed.length ? completed.reduce((total, job) => total + (new Date(job.completedAt!).getTime() - new Date(job.createdAt).getTime()) / 3_600_000, 0) / completed.length : 0; return { completed: completed.length, repeated: repeated.length, active: active.length, averageHours: Number(averageHours.toFixed(1)), completedThisMonth: completed.filter((job) => job.completedAt?.startsWith("2026-07")).length }; }
export function monthlyPerformance(employeeId: string, jobs: Job[]) { const assigned = employeeJobs(employeeId, jobs); return months.map((month) => ({ month: new Date(`${month}-01T00:00:00Z`).toLocaleDateString("en-KE", { month: "short" }), completed: assigned.filter((job) => job.completedAt?.startsWith(month)).length, repeated: assigned.filter((job) => job.completedAt?.startsWith(month) && job.repeatGroupId).length, workload: assigned.filter((job) => job.createdAt.startsWith(month) && openStatuses.includes(job.status)).length })); }
export function employeeAchievements(employee: Employee, jobs: Job[]) { const metrics = employeeMetrics(employee, jobs); const achievements = []; if (metrics.completed >= 25) achievements.push({ title: "Reliable closer", detail: `${metrics.completed} completed jobs in the sample period.` }); if (metrics.repeated >= 5) achievements.push({ title: "Repeat-work specialist", detail: `${metrics.repeated} recurring jobs successfully handled.` }); if (metrics.active < 5 && employee.availability === "active") achievements.push({ title: "Capacity ready", detail: "Available for the next dispatch decision." }); if (!achievements.length) achievements.push({ title: "Team contributor", detail: "Consistent participation in the field operation." }); return achievements; }
export function rankedEmployees(employees: Employee[], jobs: Job[]) { return employees.filter((employee) => employee.role === "technician").map((employee) => ({ employee, metrics: employeeMetrics(employee, jobs) })).sort((a, b) => b.metrics.completed - a.metrics.completed); }
