"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { Archive, BarChart3, BriefcaseBusiness, FileBarChart, LayoutDashboard, Palette, Settings, Shield, Users, X } from "lucide-react";
import { useAuth } from "@/components/auth/auth-provider";
import { cn } from "@/lib/utils";

const navigation = [{ label: "Overview", href: "/", icon: LayoutDashboard, roles: ["super_admin", "supervisor", "admin"] }, { label: "Jobs", href: "/jobs", icon: BriefcaseBusiness, roles: ["super_admin", "supervisor", "admin"] }, { label: "Dispatch Board", href: "/dispatch", icon: BarChart3, roles: ["super_admin", "supervisor"] }, { label: "Employees", href: "/employees", icon: Users, roles: ["super_admin", "supervisor", "admin"] }, { label: "Reports", href: "/reports", icon: FileBarChart, roles: ["super_admin", "admin"] }, { label: "Archive", href: "/archive", icon: Archive, roles: ["super_admin", "admin"] }, { label: "Design System", href: "/showcase", icon: Palette, roles: ["super_admin", "supervisor", "admin"] }];

export function Sidebar({ mobileOpen, onClose }: { mobileOpen: boolean; onClose: () => void }) { const { user } = useAuth(); const pathname = usePathname(); const visible = navigation.filter((item) => user && item.roles.includes(user.role)); return <><button aria-label="Close navigation overlay" className={cn("fixed inset-0 z-40 bg-slate-950/45 lg:hidden", mobileOpen ? "block" : "hidden")} onClick={onClose} /><aside className={cn("fixed inset-y-0 left-0 z-50 flex w-72 flex-col bg-[var(--sidebar)] px-4 py-5 text-[var(--sidebar-foreground)] transition-transform duration-200 lg:translate-x-0", mobileOpen ? "translate-x-0" : "-translate-x-full")}><div className="flex items-center justify-between px-3"><Link href="/" className="flex items-center gap-3" onClick={onClose}><span className="grid h-9 w-9 place-items-center rounded-lg bg-primary text-lg font-bold text-white">O</span><span className="text-xl font-semibold tracking-tight">Operax</span></Link><button className="rounded-md p-2 text-[var(--sidebar-muted)] hover:bg-white/10 lg:hidden" aria-label="Close navigation" onClick={onClose}><X className="h-5 w-5" /></button></div><div className="mt-10 px-3 text-xs font-semibold uppercase tracking-[0.14em] text-[var(--sidebar-muted)]">Workspace</div><nav className="mt-3 space-y-1" aria-label="Primary navigation">{visible.map(({ label, href, icon: Icon }) => <Link key={label} href={href} onClick={onClose} className={cn("flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium transition-colors", pathname === href ? "bg-white/14 text-white" : "text-[var(--sidebar-muted)] hover:bg-white/10 hover:text-white")}><Icon className="h-[18px] w-[18px]" />{label}</Link>)}</nav><div className="mt-auto border-t border-white/10 pt-4"><Link href="/settings" onClick={onClose} className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium text-[var(--sidebar-muted)] hover:bg-white/10 hover:text-white"><Settings className="h-[18px] w-[18px]" />Settings</Link><div className="mt-3 flex items-center gap-3 px-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-white/10"><Shield className="h-4 w-4" /></span><span className="min-w-0"><span className="block truncate text-sm font-medium text-white">{user?.name}</span><span className="block text-xs capitalize text-[var(--sidebar-muted)]">{user?.role.replace("_", " ")}</span></span></div></div></aside></>; }
