"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";
import { useAuth } from "@/components/auth/auth-provider";
import { operationsData } from "@/lib/mock-data/operations-data";
import type { Job, JobActivity, JobPriority, JobStatus } from "@/types/operations";

type JobInput = Pick<Job, "title" | "description" | "clientId" | "categoryId" | "priority" | "scheduledFor"> & Partial<Pick<Job, "status" | "primaryTechnicianId" | "supportingTechnicianIds" | "resolution" | "cancellationReason" | "blockerReason" | "photos">>;
interface JobStoreValue { jobs: Job[]; ready: boolean; createJob: (input: JobInput) => Job; updateJob: (id: string, updates: Partial<Job>, overrideOverload?: boolean) => { job?: Job; overloadWarning?: string }; getJob: (id: string) => Job | undefined; isOverloaded: (technicianId: string) => boolean; }
const JobStoreContext = createContext<JobStoreValue | undefined>(undefined);
const STORE_KEY = "operax-demo-jobs";
const openStatuses: JobStatus[] = ["assigned", "scheduled", "in_progress", "blocked"];
const newActivity = (actor: string, type: JobActivity["type"], message: string): JobActivity => ({ id: `activity-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`, createdAt: new Date().toISOString(), actor, type, message });

export function JobStoreProvider({ children }: React.PropsWithChildren) {
  const { user } = useAuth(); const [jobs, setJobs] = useState<Job[]>(operationsData.jobs); const [ready, setReady] = useState(false);
  useEffect(() => { const stored = window.localStorage.getItem(STORE_KEY); if (stored) setJobs(JSON.parse(stored)); setReady(true); }, []);
  useEffect(() => { if (ready) window.localStorage.setItem(STORE_KEY, JSON.stringify(jobs)); }, [jobs, ready]);
  const isOverloaded = (technicianId: string) => jobs.filter((job) => job.primaryTechnicianId === technicianId && openStatuses.includes(job.status)).length >= 5;
  const createJob = (input: JobInput) => { const now = new Date().toISOString(); const number = Math.max(...jobs.map((job) => Number(job.reference.slice(4))), 0) + 1; const equipment = operationsData.equipment[0]; const job: Job = { id: `work-order-${String(number).padStart(4, "0")}`, reference: `WO-${String(number).padStart(4, "0")}`, title: input.title, description: input.description, clientId: input.clientId, categoryId: input.categoryId, equipmentId: equipment.id, plantSection: equipment.plantSection, priority: input.priority, status: input.status ?? (input.primaryTechnicianId ? "assigned" : "reported"), primaryTechnicianId: input.primaryTechnicianId, supportingTechnicianIds: input.supportingTechnicianIds ?? [], supervisorId: operationsData.employees.find((employee) => employee.role === "supervisor")!.id, createdAt: now, updatedAt: now, scheduledFor: input.scheduledFor, resolution: input.resolution, cancellationReason: input.cancellationReason, blockerReason: input.blockerReason, photos: input.photos ?? [], activity: [newActivity(user?.name ?? "Operax User", "created", "Created this work order")] }; setJobs((current) => [job, ...current]); return job; };
  const updateJob = (id: string, updates: Partial<Job>, overrideOverload = false) => { const existing = jobs.find((job) => job.id === id); if (!existing) return {}; if (updates.primaryTechnicianId && updates.primaryTechnicianId !== existing.primaryTechnicianId && isOverloaded(updates.primaryTechnicianId) && !overrideOverload) return { overloadWarning: "This technician already has five or more open jobs. Assign anyway?" }; const nextStatus = updates.status ?? existing.status; if (nextStatus === "completed" && !(updates.resolution ?? existing.resolution)?.trim()) throw new Error("A resolution summary is required to complete a job."); if (nextStatus === "cancelled" && !(updates.cancellationReason ?? existing.cancellationReason)?.trim()) throw new Error("A cancellation reason is required."); if (nextStatus === "blocked" && !(updates.blockerReason ?? existing.blockerReason)?.trim()) throw new Error("A blocker reason is required."); const changes: string[] = []; if (updates.status && updates.status !== existing.status) changes.push(`Changed status to ${updates.status.replace("_", " ")}`); if (updates.priority && updates.priority !== existing.priority) changes.push(`Changed priority to ${updates.priority}`); if (updates.primaryTechnicianId && updates.primaryTechnicianId !== existing.primaryTechnicianId) changes.push("Assigned a technician"); if (updates.photos && updates.photos.length > (existing.photos?.length ?? 0)) changes.push("Added job photo(s)"); if (updates.title && updates.title !== existing.title) changes.push("Updated job details"); const statusChanged = updates.status && updates.status !== existing.status; const updated: Job = { ...existing, ...updates, completedAt: nextStatus === "completed" ? existing.completedAt ?? new Date().toISOString() : updates.completedAt ?? existing.completedAt, updatedAt: new Date().toISOString(), activity: [...(existing.activity ?? []), newActivity(user?.name ?? "Operax User", statusChanged ? "status_changed" : updates.photos ? "photo_added" : updates.primaryTechnicianId ? "assigned" : "updated", changes.join(" · ") || "Updated job")] }; setJobs((current) => current.map((job) => job.id === id ? updated : job)); return { job: updated }; };
  const value = useMemo(() => ({ jobs, ready, createJob, updateJob, getJob: (id: string) => jobs.find((job) => job.id === id), isOverloaded }), [jobs, ready]);
  return <JobStoreContext.Provider value={value}>{children}</JobStoreContext.Provider>;
}
export function useJobs() { const value = useContext(JobStoreContext); if (!value) throw new Error("useJobs must be used within JobStoreProvider"); return value; }
export type { JobInput, JobPriority };
